export type AuditAction =
  | "ADMIN_LOGIN_SUCCESS"
  | "ADMIN_LOGIN_FAILED"
  | "STUDENT_LOGIN_SUCCESS"
  | "STUDENT_LOGIN_FAILED"
  | "LOGOUT"
  | "PASSWORD_CHANGED"
  | "PASSWORD_RESET_REQUESTED"
  | "STUDENT_CREATED"
  | "STUDENT_UPDATED"
  | "STUDENT_ACTIVATED"
  | "STUDENT_DEACTIVATED"
  | "STUDENT_SOFT_DELETED"
  | "STUDENT_PERMANENT_DELETE_ATTEMPT"
  | "ENROLLMENT_CREATED"
  | "ENROLLMENT_UPDATED"
  | "ENROLLMENT_REVOKED"
  | "ENROLLMENT_REACTIVATED"
  | "PAYMENT_APPROVED"
  | "PAYMENT_REJECTED"
  | "PAYMENT_UPDATED"
  | "MANUAL_RECORDING_UNLOCK_GRANTED"
  | "MANUAL_RECORDING_UNLOCK_REVOKED"
  | "MANUAL_MATERIAL_UNLOCK_GRANTED"
  | "MANUAL_MATERIAL_UNLOCK_REVOKED"
  | "RECORDING_CREATED"
  | "RECORDING_UPDATED"
  | "RECORDING_PUBLISHED"
  | "RECORDING_UNPUBLISHED"
  | "RECORDING_DELETED"
  | "MATERIAL_UPLOADED"
  | "MATERIAL_UPDATED"
  | "MATERIAL_PUBLISHED"
  | "MATERIAL_UNPUBLISHED"
  | "MATERIAL_DELETED"
  | "MATERIAL_DOWNLOAD_ALLOWED"
  | "MATERIAL_DOWNLOAD_DENIED"
  | "RECORDING_VIEW_ALLOWED"
  | "RECORDING_VIEW_DENIED"
  | "PROMOTION_CREATED"
  | "PROMOTION_UPDATED"
  | "PROMOTION_DELETED"
  | "SITE_SETTING_UPDATED"
  | "UNAUTHORIZED_ADMIN_API_ACCESS"
  | "SESSION_LOCK_MISMATCH";

export const AUDIT_ACTIONS = {
  ADMIN_LOGIN_SUCCESS: "Admin Login Success",
  ADMIN_LOGIN_FAILED: "Admin Login Failed",
  STUDENT_LOGIN_SUCCESS: "Student Login Success",
  STUDENT_LOGIN_FAILED: "Student Login Failed",
  LOGOUT: "Logout",
  PASSWORD_CHANGED: "Password Changed",
  PASSWORD_RESET_REQUESTED: "Password Reset Requested",
  STUDENT_CREATED: "Student Created",
  STUDENT_UPDATED: "Student Updated",
  STUDENT_ACTIVATED: "Student Activated",
  STUDENT_DEACTIVATED: "Student Deactivated",
  STUDENT_SOFT_DELETED: "Student Soft Deleted",
  STUDENT_PERMANENT_DELETE_ATTEMPT: "Student Permanent Delete Attempt",
  ENROLLMENT_CREATED: "Enrollment Created",
  ENROLLMENT_UPDATED: "Enrollment Updated",
  ENROLLMENT_REVOKED: "Enrollment Revoked",
  ENROLLMENT_REACTIVATED: "Enrollment Reactivated",
  PAYMENT_APPROVED: "Payment Approved",
  PAYMENT_REJECTED: "Payment Rejected",
  PAYMENT_UPDATED: "Payment Updated",
  MANUAL_RECORDING_UNLOCK_GRANTED: "Manual Recording Unlock Granted",
  MANUAL_RECORDING_UNLOCK_REVOKED: "Manual Recording Unlock Revoked",
  MANUAL_MATERIAL_UNLOCK_GRANTED: "Manual Material Unlock Granted",
  MANUAL_MATERIAL_UNLOCK_REVOKED: "Manual Material Unlock Revoked",
  RECORDING_CREATED: "Recording Created",
  RECORDING_UPDATED: "Recording Updated",
  RECORDING_PUBLISHED: "Recording Published",
  RECORDING_UNPUBLISHED: "Recording Unpublished",
  RECORDING_DELETED: "Recording Deleted",
  MATERIAL_UPLOADED: "Material Uploaded",
  MATERIAL_UPDATED: "Material Updated",
  MATERIAL_PUBLISHED: "Material Published",
  MATERIAL_UNPUBLISHED: "Material Unpublished",
  MATERIAL_DELETED: "Material Deleted",
  MATERIAL_DOWNLOAD_ALLOWED: "Material Download Allowed",
  MATERIAL_DOWNLOAD_DENIED: "Material Download Denied",
  RECORDING_VIEW_ALLOWED: "Recording View Allowed",
  RECORDING_VIEW_DENIED: "Recording View Denied",
  PROMOTION_CREATED: "Promotion Created",
  PROMOTION_UPDATED: "Promotion Updated",
  PROMOTION_DELETED: "Promotion Deleted",
  SITE_SETTING_UPDATED: "Site Setting Updated",
  UNAUTHORIZED_ADMIN_API_ACCESS: "Unauthorized Admin API Access",
  SESSION_LOCK_MISMATCH: "Session Lock Mismatch",
} as const;
